# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 1433:1433
    secrets:
      - db_password

  # storage:
  #   image: mcr.microsoft.com/azure-storage/azurite
  #   ports:
  #     - 10000:10000
  #     - 10001:10001
  #     - 10002:10002
  #   volumes:
  #     - /data:./_data

  api:
    image: api
    build:
      context: .
      dockerfile: ./MyApp.Api/Dockerfile
    environment:
      ConnectionStrings__Comics:
    ports:
      - 5000:5000
    depends_on:
      - db
      - storage
    secrets:
      - source: connection_string
        target: ConnectionStrings__Comics

secrets:
  db_password:
    file: ./.local/db_password.txt
  connection_string:
    file: ./.local/connection_string.txt
